### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by nonk123** [WhatNodyn/kakoune-wakatime#16]
It's been a while since the last commit. Does this plugin still work?

**Comment by alanhamlett** [comment]
No, it doesn't work. I'll create a fork and get it working.

The main blocker is #12, but it also looks like the api key isn't persisting.

**Comment by alanhamlett** [comment]
The version at https://github.com/wakatime/kakoune-wakatime is working now.

**Comment by nonk123** [comment]
Awesome! I'll check it out as soon as I'm back home.
