### ISSUE TITLE
No such command error/No statistics in Wakatime Dashboard - Kakoune 2019.07.01

### ISSUE THREAD

**Issue by ahoward1024** [WhatNodyn/kakoune-wakatime#6]
When installing this plugin on a fresh version of Kakoune 2019.07.01, a `no such command` error is thrown at all `echo` statements in the plugin file.

Also, no statistics for Kakoune show up in the Wakatime dashboard.

To reproduce you can use docker and the latest version of Ubutunu:
```
docker pull ubuntu:18.10
docker run -it ubuntu:18.10 bash
```
Then, in the container:
```
cd ~
apt update && apt install git make libncursesw5-dev pkg-config python unzip wget -y
git clone https://github.com/mawww/kakoune.git
cd kakoune/src/
make && make install
git clone https://github.com/WhatNodyn/kakoune-wakatime.git
mkdir -p ~/.config/kak/autoload
cp kakoune-wakatime/wakatime.kak ~/.config/kak/autoload
kak
```
If you then `:buffer *debug*` in Kakoune, you will see an error with:
`'wakatime-init' no such command: 'echo -debug ...'` regardless of whether Wakatime is installed or not.

If Wakatime is installed and properly configured, no statistics show up in the Dashboard.

This is due to Kakoune requiring `evaluate-commands` _before_ each `%sh{...}` block.

**Comment by WhatNodyn** [comment]
Fixed by pull request #7
